### ISSUE TITLE
Routes folder is not attached

### ISSUE THREAD

**Issue by leenaali1114** [Nihal-Srivastava05/Cryptocurrency-Prediction-With-Sentiment-Analysis#7]
Could you please upload the routes folder too. Thanks

**Comment by Nihal-Srivastava05** [comment]
I built this using Flask backend and core HTML, CSS, and JS. The backend routes are in app.py in the deployment folder and all the webpages are linked directly to it (using the render_template() function of Flask). I haven't used React Js for it, So I am not sure what you mean by routes folder here.

**Comment by leenaali1114** [comment]
Hi Nihal,
Thank you for the reply. I keep getting an error saying that the apikeys
module is nott found. I tried commenting the line, but the api key is not
working then. Could you please help me here.

Thanks and regards
Leena Ali

**Comment by Nihal-Srivastava05** [comment]
apikeys is not a module, It is a python file I made to store the keys and credentials. As there is real time twitter tweets sentiment analysis in this we need to real time fetch the tweets from twitter. For this I made use of tweepy which requires API token of twitter. These can be got from the official twitter developer page. Here is a link which might be helpful: 

https://developer.twitter.com/en/docs/twitter-api/getting-started/getting-access-to-the-twitter-api

**Comment by leenaali1114** [comment]
Thanks, I'll check it out. Could you also please let me know where i need
to update the api key?

**Comment by Nihal-Srivastava05** [comment]
The bearer token must be added in line 46 in app.py within deployment folder. 

https://github.com/Nihal-Srivastava05/Cryptocurrency-Prediction-With-Sentiment-Analysis/blob/main/deployment/app.py#L46

**Comment by leenaali1114** [comment]
Hi Nihal,
Could you please help me with the apikeys file? What all has to be added? I
have added the bearer token and it's working fine now. Please find the
error page attached with the mail.

**Comment by leenaali1114** [comment]
Hi,
Could you please help me with my query? Also, is there a utils file?

Thankyou

**Comment by Nihal-Srivastava05** [comment]
This project only needs the bearertoken token to work. I had also added the rest in my apikey files just for reference. The other tokens include: ckey, csecret, atoken, asecret,  bearertoken (c - consumer, a - access). There is no utils file here. Few models were too large to store in github so I couldn't upload them if that is causing an issue, you can just re run all the .ipy notebooks and that should create all the models.

**Comment by leenaali1114** [comment]
Thanks, I'll check them out. What about the error I have shared the image
of?

**Comment by Nihal-Srivastava05** [comment]
I cannot find any error page image in the mail. Can you please re share it?

**Comment by leenaali1114** [comment]
Please check now.

**Comment by Nihal-Srivastava05** [comment]
![image](https://github.com/Nihal-Srivastava05/Cryptocurrency-Prediction-With-Sentiment-Analysis/assets/82692408/a67313f9-4fc1-4c14-9d66-534a11897daf)

Am I looking in the wrong place? It is blank at my end. If possible just attach the output here in GitHub itself.

**Comment by leenaali1114** [comment]
![Screenshot (3)](https://github.com/Nihal-Srivastava05/Cryptocurrency-Prediction-With-Sentiment-Analysis/assets/67731093/9b5433d7-4564-4bd7-92e6-7faacd9cef70)
 Please check

**Comment by Nihal-Srivastava05** [comment]
I think you haven't created any apps in your twitter developer dashboard. You need to create a new app and connect it there.

**Comment by Nihal-Srivastava05** [comment]
Does this solve the problem... do you have any more issues?

**Comment by leenaali1114** [comment]
Not really. I created the app and did everything but the error persists. It
would be really helpful if you could send me the complete project. So i can
refer the error. Or atleast the important files. Please consider my request.
Thanks

**Comment by Nihal-Srivastava05** [comment]
This is the complete project, The only files I have not included in the repo is apikeys.py as it has my twitter API keys. You might have to allow your computers or server IP address in the twitter key settings or if it is local set it to 0.0.0.0 or 127.0.0.1, The error does not look to be due to any issue in the project but the twitter part only. Maybe try to comment the sentiment analysis endpoints to make sure.

**Comment by leenaali1114** [comment]
Thank you for the help!
